In [7]:
X = df.drop(['MPG'],axis=1)
y = df.MPG

In [8]:
X['Origin'] = X['Origin'].map({1: 'USA', 2: 'Europe', 3: 'Japan'})
X = pd.get_dummies(X, prefix='', prefix_sep='')
X.tail()

,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Europe,Japan,USA
393,4,140.0,86.0,2790.0,15.6,82,0,0,1
394,4,97.0,52.0,2130.0,24.6,82,1,0,0
395,4,135.0,84.0,2295.0,11.6,82,0,0,1
396,4,120.0,79.0,2625.0,18.6,82,0,0,1
397,4,119.0,82.0,2720.0,19.4,82,0,0,1

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [10]:
X_train_stats = X_train.describe()
X_train_stats = X_train_stats.transpose()
X_train_stats

,count,mean,std,min,25%,50%,75%,max
Cylinders,274.0,5.543796,1.724606,3.0,4.0,5.5,8.00,8.0
Displacement,274.0,201.104015,107.295581,68.0,108.0,156.0,302.00,455.0
Horsepower,274.0,107.010949,40.528512,46.0,78.0,95.0,132.75,230.0
Weight,274.0,3029.569343,856.983519,1755.0,2280.5,2869.0,3641.75,5140.0
Acceleration,274.0,15.427007,2.809495,8.0,13.5,15.4,17.00,24.8
Model Year,274.0,75.799270,3.687401,70.0,73.0,76.0,79.00,82.0
Europe,274.0,0.138686,0.346251,0.0,0.0,0.0,0.00,1.0
Japan,274.0,0.211679,0.409246,0.0,0.0,0.0,0.00,1.0
USA,274.0,0.649635,0.477957,0.0,0.0,1.0,1.00,1.0

In [11]:
def norm(x):
    return (x - X_train_stats['mean']) / X_train_stats['std']
X_train = norm(X_train)
X_test = norm(X_test)